"""Regenerate crawlable artifacts from blog/eng/posts.js.

Run after any edit to posts.js:

    uv run scripts/build_site.py

Writes/updates:
  - index.html   (static post cards between the BUILD:eng-posts markers)
  - sitemap.xml
  - rss.xml
  - robots.txt
"""

import json
import re
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_URL = "https://gpazevedo.github.io"
SITE_TITLE = "Gustavo Peixoto de Azevedo"
FEED_TITLE = "Gustavo Azevedo — Engineering Blog"
FEED_DESCRIPTION = (
    "Technical deep-dives on agentic and generative AI, the large-scale "
    "distributed systems underneath them, and what both mean for the business."
)


def load_posts() -> list[dict]:
    text = (ROOT / "blog/eng/posts.js").read_text()
    array_text = text[text.index("[") : text.rindex("]") + 1]
    posts = json.loads(array_text)
    posts.sort(key=lambda p: p["date"], reverse=True)
    return posts


def fmt_date_human(iso_date: str) -> str:
    return datetime.strptime(iso_date, "%Y-%m-%d").strftime("%b %Y")


def render_eng_cards(posts: list[dict]) -> str:
    cards = []
    for p in posts:
        cards.append(
            f'          <a href="blog/eng/{p["file"]}" class="blog-post">\n'
            f'            <div class="blog-post-tag">{p["tags"][0]}</div>\n'
            f'            <div class="blog-post-title">{p["title"]}</div>\n'
            f'            <div class="blog-post-desc">{p["description"]}</div>\n'
            f'            <div class="blog-post-meta">{p["readingTime"]} min read · {fmt_date_human(p["date"])}</div>\n'
            f"          </a>"
        )
    return "\n".join(cards)


def update_index_html(posts: list[dict]) -> None:
    index_path = ROOT / "index.html"
    html = index_path.read_text()
    start = "<!-- BUILD:eng-posts:START — generated by scripts/build_site.py from blog/eng/posts.js, do not edit by hand -->"
    end = "<!-- BUILD:eng-posts:END -->"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    replacement = f"{start}\n{render_eng_cards(posts)}\n{end}"
    new_html, count = pattern.subn(replacement, html)
    if count != 1:
        raise RuntimeError("BUILD:eng-posts markers not found (or found more than once) in index.html")
    index_path.write_text(new_html)


def write_sitemap(posts: list[dict]) -> None:
    home_lastmod = max(p["date"] for p in posts)
    urls = [(f"{BASE_URL}/", home_lastmod)]
    urls += [(f"{BASE_URL}/blog/eng/{p['file']}", p["date"]) for p in posts]

    entries = "\n".join(
        f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{lastmod}</lastmod>\n  </url>"
        for loc, lastmod in urls
    )
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{entries}\n"
        "</urlset>\n"
    )
    (ROOT / "sitemap.xml").write_text(xml)


def write_rss(posts: list[dict]) -> None:
    def rfc822(iso_date: str) -> str:
        dt = datetime.strptime(iso_date, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        return format_datetime(dt)

    items = []
    for p in posts:
        link = f"{BASE_URL}/blog/eng/{p['file']}"
        categories = "".join(f"\n      <category>{t}</category>" for t in p["tags"])
        items.append(
            "    <item>\n"
            f"      <title>{p['title']}</title>\n"
            f"      <link>{link}</link>\n"
            f"      <guid>{link}</guid>\n"
            f"      <pubDate>{rfc822(p['date'])}</pubDate>\n"
            f"      <description>{p['description']}</description>{categories}\n"
            "    </item>"
        )

    build_date = rfc822(max(p["date"] for p in posts))
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n'
        "<channel>\n"
        f"  <title>{FEED_TITLE}</title>\n"
        f"  <link>{BASE_URL}/</link>\n"
        f'  <atom:link href="{BASE_URL}/rss.xml" rel="self" type="application/rss+xml"/>\n'
        f"  <description>{FEED_DESCRIPTION}</description>\n"
        "  <language>en-us</language>\n"
        f"  <lastBuildDate>{build_date}</lastBuildDate>\n"
        + "\n".join(items)
        + "\n</channel>\n</rss>\n"
    )
    (ROOT / "rss.xml").write_text(xml)


def write_robots() -> None:
    (ROOT / "robots.txt").write_text(
        "User-agent: *\nAllow: /\n\nSitemap: " + BASE_URL + "/sitemap.xml\n"
    )


def main() -> None:
    posts = load_posts()
    update_index_html(posts)
    write_sitemap(posts)
    write_rss(posts)
    write_robots()
    print(f"Regenerated index.html, sitemap.xml, rss.xml, robots.txt from {len(posts)} posts.")


if __name__ == "__main__":
    main()
